# Operations on Matrices

Matrix is a two-dimensional array where numbers, symbols or expressions are arranged into rows and columns. Using the concept of lists, one can easily define a matrix in Python. <br>
We define two matrices A and B.

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[9,8,7],[6,5,4],[3,2,1]]
print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


We use the following commands to access the elements of a matrix.

In [ ]:
A[0][0] # A single element is called

1

In [ ]:
A[1] # The second row is called

[4, 5, 6]

In [ ]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]

Write a program to add to matrices A and B.

In [ ]:
sum=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(A)):
    for j in range(len(A[0])):
        sum[i][j] = A[i][j]+B[i][j]
print(sum)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [ ]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A*B #The multiplication operator does not work when the matrix is defined as list of lists

In [ ]:
A**2 #The ** opertor or pow() does not work when the matrix is defined as list of lists

### Exercise: 
1. Write a program to multiply two matrices.
2. Write a program to find the transpose of a matrix.
3. Write a program to find the square root of each element of a matrix.

In [ ]:
A[0].append(10)
print(A)

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]


The matrix A being defined as a list of lists, Python supports adding a single element to a row or column, which falsifies the very definition of a matrix.

Through the above commands, we can see that even though it is possible to define matrix as a list of lists, matrix manipulation is not straight forward as desired. 

#### Working with matrices can be made easier in Python using NumPy package

NumPy is a library consisting of multidimensional array obejects and package
of functions for processing those arrays. NumPy stands for Numerical Python. 
The following operations can be performed using NumPy. 
1. Mathematical and logical operations on arrays.
2. Fourier transforms and routines for shape manipulation.
3. Operations related to linear algebra.
We can import the NumPy package using one of the following syntax- <br>
import numpy <br>
import numpy as np (preferred) <br>
from numpy import * 

In [2]:
import numpy as np

NumPy provides the function array() and matrix() to define a matrix. 

In [ ]:
A1=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(A1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
M1=np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print(M1)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


The differences between np.array() and np.matrix() are the following:
1. np.array() provides an n-dimensional array while np.matrix() is
   strictly 2-dimensional.
3. The \* and \*\* operators performs elementwise operations in
   array while in matrix they are used for multipication and finding powers.

We will use np.matrix() to work with matrices. 
Frequent errors while defining a matrix are shown below.

In [5]:
N=np.matrix[[1,2,3],[3,4,5],[5,6,7]]

TypeError: ignored

In [6]:
N=np.matrix([1,2,3],[3,4,5],[5,6,7])

TypeError: ignored

N=np.matrix([[1,2,3],[3,4,5],[5,6,7]])

## Matrix Manipulation

The order of the matrix can be found using the shape function.

In [6]:
M1=np.matrix([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
M1.shape

(3, 4)

In [12]:
print(M1.shape[0]) # Number of rows
print(M1.shape[1]) # number of columns

3
4


The number of elements in the matrix is given by size function.

In [14]:
M1.size # Number of rows X Number of columns

12

The function zeros creates an array of zeros.

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Note that zeros produces an array of zeros rather than a matrix.

In [ ]:
Z=np.zeros((4,4))

In [ ]:
Zm=np.matrix(Z)

In [ ]:
Zm

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Matrix operations

The + operator and the function add() can be used to add corresponding elements of two matrices.

In [ ]:
D=np.matrix([[1,2,3],[3,4,5],[5,6,7]])
E=np.matrix([[3,2,9],[3,8,1],[1,0,7]])
F=np.matrix([[11,2,3],[3,10,7],[5,8,2]])

In [ ]:
D+E

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

In [ ]:
np.add(D,E)

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

The - operator and the function subtract() can be used to subtract corresponding elements of the second matrix from the first.

In [ ]:
D-E

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

In [ ]:
np.subtract(D,E)

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

The multiply() function is used for elementwise multiplication 
and \* operator and .dot() function can be used for matrix multipication.

In [ ]:
np.multiply(D,E) # element wise multiplication

matrix([[ 3,  4, 27],
        [ 9, 32,  5],
        [ 5,  0, 49]])

In [ ]:
D*E # actual matrix multiplication

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [ ]:
D.dot(E) # actual matrix multiplication

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

The / operator and the function divide can be used for element wise matrix division.

In [ ]:
E/D

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

In [ ]:
np.divide(E,D)

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

Transpose of a matrix can be found using transpose() function and .T operator.

In [ ]:
D.transpose()

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [ ]:
np.transpose(D)

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [ ]:
D.T

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

### Accessing matrix elements, rows and columns

In [ ]:
print(D[1,2]) # Accessing an element

5


In [ ]:
print(D[0]) # Accessing a row

[[1 2 3]]


In [ ]:
print(D[:, 2]) # Accessing a column

[[3]
 [5]
 [7]]


Slicing a is possible using the colon operator.

In [ ]:
G=np.matrix([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(G)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(G[:2, :4])

[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
print(G[:1,])

[[1 2 3 4 5]]


In [ ]:
print(G[0,])

[[1 2 3 4 5]]


In [ ]:
print(G[:,2])

[[ 3]
 [ 8]
 [13]
 [18]
 [23]]


In [ ]:
print(G[1:4, 1:4]) 

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
