# Diagonal matrix

In [2]:
import numpy as np
X=np.zeros((3,3))
np.fill_diagonal(X,1)
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Display identity matrix of order 4

In [3]:
i4 = np.matrix(np.eye(4))
print(i4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Check the commutativity for addition and multiplication of matrices and display the result.

$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}$

$B=\begin{bmatrix}
-1 & 4 & 0 \\
2 & 3 & 1 \\
2 & 1 & 0 \\
\end{bmatrix}$

In [4]:
A = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.matrix([[-1, 4, 0], [2, 3, 1], [2, 1, 0]])

In [5]:
# Addition
print("A =", A)
print("B =", B)
print("A+B =", A+B)
print("B+A =", B+A)
if np.allclose(A+B, B+A):
    print("A+B = B+A")
    print("Hence, matrix addition is commutative")
else:
    print("A+B != B+A")
    print("Hence, matrix addition is not commutative")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[-1  4  0]
 [ 2  3  1]
 [ 2  1  0]]
A+B = [[0 6 3]
 [6 8 7]
 [9 9 9]]
B+A = [[0 6 3]
 [6 8 7]
 [9 9 9]]
A+B = B+A
Hence, matrix addition is commutative


In [6]:
# Multiplication
print("A =", A)
print("B =", B)
print("AB = ", A*B)
print("BA = ", B*A)
if np.allclose(A*B, B*A):
    print("AB = BA")
    print("Hence, matrix multiplication is commutative")
else:
    print("AB != BA")
    print("Hence, matrix multiplication is not commutative")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[-1  4  0]
 [ 2  3  1]
 [ 2  1  0]]
AB =  [[ 9 13  2]
 [18 37  5]
 [27 61  8]]
BA =  [[15 18 21]
 [21 27 33]
 [ 6  9 12]]
AB != BA
Hence, matrix multiplication is not commutative


# Trace of the matrix
np.trace()

$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}$

In [7]:
A = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.trace(A)

15

# Find $A^3 - 3A + 20I$

In [19]:
A = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6], [5, 4, 3, 2]])
eq = A**3 - 3*A + 20*np.identity(4)
print("A^3 - 3A + 20I =\n", eq)

6.0

Express the Matrix
$$\begin{bmatrix} 2 & 3 & 1 \\ 4 & -2 & 0 \\ 13 & -1 & 5\end{bmatrix}$$
as sum of symmetric and skew symmetric matrices.</b>

In [8]:
A=np.array([[2,3,1],[4,-2,0],[3,-1,5]])
B=np.identity(3,dtype=int)
print("Matrix \n",A)
T=np.transpose(A)
print("\nTranspose of A \n",T)
sol1=(A+T)/2
print("Symmetric matrix")
print("\n(A + A^T)/2= \n",sol1)
sol2=(A-T)/2
print("Skew Symmetric matrix.")
print("\n(A - A^T)/2= \n",sol2)
ans=sol1+sol2
print("\nAnswer = \n",ans)
print("\nTherefore, A = sum of symmetric and skew symmetric matrix")

Matrix 
 [[ 2  3  1]
 [ 4 -2  0]
 [ 3 -1  5]]

Transpose of A 
 [[ 2  4  3]
 [ 3 -2 -1]
 [ 1  0  5]]
Symmetric matrix

(A + A^T)/2= 
 [[ 2.   3.5  2. ]
 [ 3.5 -2.  -0.5]
 [ 2.  -0.5  5. ]]
Skew Symmetric matrix.

(A - A^T)/2= 
 [[ 0.  -0.5 -1. ]
 [ 0.5  0.   0.5]
 [ 1.  -0.5  0. ]]

Answer = 
 [[ 2.  3.  1.]
 [ 4. -2.  0.]
 [ 3. -1.  5.]]

Therefore, A = sum of symmetric and skew symmetric matrix
