## Matrices

## Matrix is a two-dimensional array where numbers, symbols or expressions are arranged into rows and columns. Using the concept of lists, one can easily define a matrix in Python. <br>
## We define two matrices A and B.

In [5]:
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[9,8,7],[6,5,4],[3,2,1]]
print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [3]:
A[0][2] # A single element is called

3

In [5]:
A[0].append(10)
print(A)

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]


The matrix A being defined as a list of lists, Python supports adding a single element to a row or column, which falsifies the very definition of a matrix.

Through the above commands, we can see that even though it is possible to define matrix as a list of lists, matrix manipulation is not straight forward as desired. 

#### Working with matrices can be made easier in Python using NumPy package

## NumPy is a library consisting of multidimensional array objects and package of functions for processing those arrays. NumPy stands for Numerical Python. The following operations can be performed using NumPy. 
## 1. Mathematical and logical operations on arrays.
## 2. Fourier transforms and routines for shape manipulation.
## 3. Operations related to linear algebra.
## We can import the NumPy package using one of the following syntax- <br>
## import numpy <br>
## import numpy as np (preferred) <br>
## from numpy import * 

In [1]:
import numpy as np

NumPy provides the function array() and matrix() to define a matrix. 

In [ ]:
A1=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(A1)

In [ ]:
M1=np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print(M1)

### The \* and \*\* operators performs elementwise operations in array while in matrix they are used for multipication and finding powers.

In [37]:

N=np.array([[1,2,3,19],[3,4,5],[5,6,7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [35]:

N=np.matrix([[1,2,3,19],[3,4,5],[5,6,7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [28]:
X=np.matrix([[1,2,3],[3,4,5],[5,6,7]])
X
print(X)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [4]:
X[0,1]

2

In [5]:
X[1,1]

4

## Matrix Manipulation

The order of the matrix can be found using the shape function.

In [6]:
X.shape

(3, 3)

In [18]:
import numpy as np
M2=np.matrix([[1,2,3],[2,3,4],[1,2,34],[1,2,3]])
print(M2.shape[0])
print(M2.shape[1])

4
3


In [12]:
M2.shape[0] # Number of rows

4

The number of elements in the matrix is given by size function.

In [14]:
M2.size # Number of rows X Number of columns

12

The function zeros creates an array of zeros.

In [8]:
np.zeros((4,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

by default the zeros() and ones() function gives float value, so the output is 0. or 1., if np.zeros(4,4, dtype=int) or simply (np.zeros(4,4, int)) is given then we get it as 0 or 1

Note that zeros produces an array of zeros rather than a matrix.

### Matrix operations

In [1]:
import numpy as np
D=np.matrix([[1,2,3],[3,4,5],[5,6,7]]) # defining 3 matrices
print("the matrix D\n", D)
E=np.matrix([[3,2,9],[3,8,1],[1,0,7]])
print("the matrix E\n", E)
F=np.matrix([[11,2,3],[3,10,7],[5,8,2]])
print("the matrix F\n", F)

the matrix D
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
the matrix E
 [[3 2 9]
 [3 8 1]
 [1 0 7]]
the matrix F
 [[11  2  3]
 [ 3 10  7]
 [ 5  8  2]]


In [3]:
A=np.zeros((3,3),dtype=float)
for i in range(0,3):
    for j in range(0,3):
        A[i,j]=D[i,j]+E[i,j] 
print(A)
        

[[ 4.  4. 12.]
 [ 6. 12.  6.]
 [ 6.  6. 14.]]


## The + operator and the function add() can be used to add corresponding elements of two matrices.

In [5]:
D+E

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

In [7]:
np.add(D,E)

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

## The - operator and the function subtract() can be used to subtract corresponding elements of the second matrix from the first.

In [10]:
np.subtract(D,E)

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

In [12]:
D-E

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

## The multiply() function is used for elementwise multiplication. 

In [14]:
np.multiply(D,E)

matrix([[ 3,  4, 27],
        [ 9, 32,  5],
        [ 5,  0, 49]])

## * operator and .dot() function can be used for matrix multipication.

In [16]:
D*E

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [18]:
D.dot(E)

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [20]:
np.dot(D,E)

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

## The / operator and the function divide() can be used for element wise matrix division.

In [23]:
D1=np.matrix([[1,2],[2,1],[3,4]])
E1=np.matrix([[1,5],[2,0],[3,4]])
A=np.zeros((3,2),dtype=int)
for i in range(3):
    for j in range(2):
        A[i,j]=D1[i,j]+E1[i,j]
print(A)   

[[2 7]
 [4 1]
 [6 8]]


In [20]:
E/D

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

In [21]:
np.divide(E,D)

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

## Transpose of a matrix

### Transpose of a matrix can be found using transpose() function and .T operator.

In [25]:
D

matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [27]:
r=np.zeros((3,3))
for i in range(D.shape[0]):
    for j in range(D.shape[1]):
        r[i,j]=D[j,i]
print(r)

[[1. 3. 5.]
 [2. 4. 6.]
 [3. 5. 7.]]


In [29]:
D.transpose()

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [31]:
np.transpose(D)

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [33]:
D.T

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

## Upper and Lower Triangular Matrix

In [35]:
D


matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [37]:
UT=np.triu(D) ## triu() is the function that is used to get the upper triangular matrix of a matrix
print(UT)

[[1 2 3]
 [0 4 5]
 [0 0 7]]


In [39]:
LT=np.tril(D) ## tril() is the function that is used to get the lower triangular matrix of a matrix
print(LT)

[[1 0 0]
 [3 4 0]
 [5 6 7]]


### numpy.linalg

## NumPy package contains numpy.linalg module 
### that provides various the functionality 
### required for linear algebra.
## One can find:

## $\bullet$ rank, determinant, trace, inverse etc. of an array <br>
## $\bullet$ eigen values of matrices <br>
## $\bullet$ matrix and vector products 
### (dot, inner, outer,etc. product),
### matrix exponentiation ,<br>
## $\bullet$ solve linear equations and much more!

## Determinant of a matrix

In [9]:
import numpy as np
D=np.array([[1,2,3],[3,4,5],[5,6,7]])
print("the matrix D=", D)

the matrix D= [[1 2 3]
 [3 4 5]
 [5 6 7]]


In [11]:
determinant=np.linalg.det(D)
print("The determinant of the matrix D is:", determinant)

The determinant of the matrix D is: 2.042810365310277e-15


## Rank of a Matrix

$A = \begin{bmatrix}1 & 7 & 5 & 6 \\ 7 & 2 & 6 & 7 \\-1 & -3 &-3 & 4\end{bmatrix}$</b>

In [5]:
import numpy as np
A = np.array(([1,7,5,6],[7,2,6,7],[-1,-3,-3,4]))
print("A=",A) 
print("\n The rank of the matrix A is",np.linalg.matrix_rank(A))

A= [[ 1  7  5  6]
 [ 7  2  6  7]
 [-1 -3 -3  4]]

 The rank of the matrix A is 3


$A = \begin{bmatrix}1 & 2 & 3\\ 2 & 1 & 4\\3 & 0 & 5\end{bmatrix}$</b>

In [7]:
import numpy as np
A = np.array(([1,2,3],[2,1,4],[3,0,5]))
print("A=",A)
print("\n The rank of the matrix A is",np.linalg.matrix_rank(A))

A= [[1 2 3]
 [2 1 4]
 [3 0 5]]

 The rank of the matrix A is 2


## Properties

If A matrix is of order mXn, then $\rho$(A) $\le$ min{m,n} = minimum of m,n.

If A is of order nXn and |A| $\neq$ 0, then the rank of A = n.

If A is of order nXn and |A| = 0, then the rank of A will be less than n

In [1]:
#Property1Example
import numpy as np
A = np.array(([4,2],[5,7],[8,9],[9,0]))
print("A=",A)
print("\n The rank of the matrix A is",np.linalg.matrix_rank(A))

A= [[4 2]
 [5 7]
 [8 9]
 [9 0]]

 The rank of the matrix A is 2


## Inverse of a matrix

In [9]:
D = np.matrix(([1,2,3],[2,1,4],[3,0,5]))
d = np.linalg.det(D)
print("determinant of D = ",d)
print("inverse of the matrix D = ", D**-1)

determinant of D =  6.66133814775094e-16
inverse of the matrix D =  [[ 7.50599938e+15 -1.50119988e+16  7.50599938e+15]
 [ 3.00239975e+15 -6.00479950e+15  3.00239975e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [11]:
Inverse=np.linalg.inv(D)
print("The inverse of the matrix D is:", Inverse)

The inverse of the matrix D is: [[ 7.50599938e+15 -1.50119988e+16  7.50599938e+15]
 [ 3.00239975e+15 -6.00479950e+15  3.00239975e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


## Reducing a matrix to Echelon form

<b> Q. Obtain the row reduced echelon form for the matrix,
$$B = \begin{bmatrix}1 & 1 & 1 \\ 3 & 1 & -2 \\2 & 4 & 7\end{bmatrix}$$</b>

In [46]:
import sympy as sp
import numpy as np
B = np.matrix(input("Enter a square matrix:"))
print("The given matrix is :\n {} ".format(B))
E = sp.Matrix(B).rref()
E

Enter a square matrix: [[1,2,3],[4,5,6],[7,8,9]]


The given matrix is :
 [[1 2 3 4 5 6 7 8 9]] 


(Matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), (0,))

In [48]:
import numpy as np
D=np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print("The given matrix is :\n {} ".format(D))
C = sp.Matrix(D).rref()
C

The given matrix is :
 [[1 2 3]
 [3 4 5]
 [6 7 8]] 


(Matrix([
 [1, 0, -1],
 [0, 1,  2],
 [0, 0,  0]]),
 (0, 1))

## Solving system of equations

<b>Syntax:</b><br>
numpy.linalg.solve(A,B)

Q. Find all solutions for the linear system<br>
$x_1 + 2x_2 - x_3 = 1$<br>
$2x_1 + x_2 +4x_3 = 2$<br>
$3x_1 + 3x_2 + 4x_3 = 1$

### Non-singular Matrix - unique solutions exist

In [54]:
import numpy as np
A = np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B = np.matrix([[1],[2],[1]])
np.linalg.solve(A,B)

matrix([[ 7.],
        [-4.],
        [-2.]])

In [56]:
A = np.array([[1,2,-1],[2,1,4],[3,3,4]])
B = np.array([1,2,1])
np.linalg.solve(A,B)

array([ 7., -4., -2.])

### Singular Matrix - unique solutions do not exist

In [5]:
A = np.matrix([[1,-1,1,-1],[1,-1,1,-1],[4,-4,4,0],[-2,2,-2,1]])
B = np.matrix([[2],[0],[4],[-3]])
np.linalg.solve(A,B) # Since the determinant of coefficient matrix is 0,
                     # its giving an error

LinAlgError: Singular matrix

Q. Check whether the following system of homogeneous linear equation has non-trivial solution.<br>
$x_1 + 2x_2 - x_3 = 0$<br>
$2x_1 + x_2 +4x_3 = 0$<br>
$3x_1 + 3x_2 + 4x_3 = 0$

In [1]:
import numpy as np
A1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B1 = np.matrix([[0],[0],[0]])
r = np.linalg.matrix_rank(A1)
n = A1.shape[1]
if (r==n):
    print("System has trivial solution")
else:
    print("System has", n-r, "non-trivial solution(s)")

System has 1 non-trivial solution(s)


In [3]:
np.linalg.solve(A1,B1)

matrix([[ 0.],
        [ 0.],
        [-0.]])

### System of Non-Homogeneous Linear Equations

Q. Examine the consistency of the following system of equations and solve if consistent<br>
$x_1 + 2x_2 - x_3 = 1$<br>
$2x_1 + x_2 + 4x_3 = 2$<br>
$3x_1 + 3x_2 + 4x_3 = 1$

In [1]:
import numpy as np
A4 = np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B4 = np.matrix([[1],[2],[1]])
AB4 = np.concatenate((A4,B4),axis=1)
rA4 = np.linalg.matrix_rank(A4)
rAB4 = np.linalg.matrix_rank(AB4)
n = A4.shape[1]
if (rA4 <= rAB4):
    if(rA4==n):
        print("The system is consistent and has unique solution")
        print(np.linalg.solve(A4,B4))
    else:
        print("The system is consistent and has infinitely many solutions")
else:
    print("The sytem of equations is inconsistent and does not have any solution")

The system is consistent and has unique solution
[[ 7.]
 [-4.]
 [-2.]]


## Eigen Values

In [13]:
import numpy as np
D1=np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print("the matrix D1=", D1)

the matrix D1= [[1 2 3]
 [3 4 5]
 [5 6 7]]


In [15]:
eigen_values= np.linalg.eigvals(D1)
print("The eigen values of the matrix D is:", eigen_values)

The eigen values of the matrix D is: [ 1.29282032e+01 -9.28203230e-01  3.74275163e-16]


In [17]:
eigen_vec=np.linalg.eig(D1)
print("The eigen values and eigen vectors of the matrix D is:", eigen_vec)

The eigen values and eigen vectors of the matrix D is: EigResult(eigenvalues=array([ 1.29282032e+01, -9.28203230e-01,  3.74275163e-16]), eigenvectors=matrix([[-0.28932501, -0.80222426,  0.40824829],
        [-0.53988782, -0.10747767, -0.81649658],
        [-0.79045062,  0.58726892,  0.40824829]]))


## Q1. Write a Python function matrix_addition(matrix1, matrix2) that takes two matrices as input (both represented as lists of lists) and returns their sum.

## Q2. Write a Python function matrix_subraction.(matrix1, matrix2) that takes two matrices as input (both represented as lists of lists) and returns subraction.

## Q3. Write a Python function matrix_malutiplication.(matrix1, matrix2) that takes two matrices as input (both represented as lists of lists) and returns the multiplication.

## Q4. Write a Python function that takes a matrix as input and returns the upper and lower triangular matrix.

In [3]:
M = eval(input("Enter the matrix as list of lists"))

Enter the matrix as list of lists [[1,2,3], [1,2,3], [1,2,3]]


In [5]:
print(M)


[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [7]:
import numpy as np 

In [9]:
A = np.array(M)

In [11]:
print(A)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
r = int(input("enter the number of rows"))

enter the number of rows 3


In [15]:
c = int(input("enter the number of columns"))

enter the number of columns 3


In [ ]:
L = []
for i in range(r):
    for j in range(c):
        L[i][j] = 

In [ ]:
#by using for loop
B = np.array([[6,2,9,5],[3,1,4,23],[4,13,2,3],[16,7,5,8]])
C = np.empty([4,4],dtype=int)
print("The Given Matrix :")
print(B)
print("Upper Triangular Matrix of the given Matrix:")
for i in range(4):
    for j in range(4):
        if j>=i:
            C[i][j]=B[i][j]
        else:
            C[i][j] = 0
print(C)
print("Lower Triangular Matrix of the given Matrix:")
D = np.empty([4,4],dtype=int)
for i in range(4):
    for j in range(4):
        if j<=i:
            D[i][j]=B[i][j]
        else:
            D[i][j] = 0
print(D)

In [ ]:
##user defined function

import numpy as np
E = np.array([[9,13,5],[1,11,7],[3,7,4]])
print("The given Matrix is:")
print(E)
det=0
submatrix = np.empty((2,2),dtype=int)
for x in range(3):
    subi = 0
    for i in range(1,3):
        subj = 0
        for j in range(3):
            if(j==x):
                continue
            else:
                submatrix[subi][subj]=E[i][j]
                subj+=1
        subi+=1
    det = det + (pow(-1, x) * E[0][x] * (submatrix[0][0]*submatrix[1][1]-submatrix[1][0]*submatrix[0][1]));
print("The Determinent of the given Matrix is :",det)

In [ ]:
import numpy as np
A7 = np.array([[2,-3,1],[4,-2,0],[3,-1,5]])
print("The given Matrix is:")
print(A7)
det=0
submatrix = np.empty((2,2),dtype=int)
for x in range(3):
    subi = 0
    for i in range(1,3):
        subj = 0
        for j in range(3):
            if(j==x):
                continue
            else:
                submatrix[subi][subj]=E[i][j]
                subj+=1
        subi+=1
    det = det + (pow(-1, x) * A7[0][x] * (submatrix[0][0]*submatrix[1][1]-submatrix[1][0]*submatrix[0][1]));
print("The Determinent of the given Matrix is :",det)

In [ ]:
##modifying particular element as None value

import numpy as np

# Input number of rows and columns
n = int(input("Enter the number of rows = "))
n1 = int(input("Enter the number of columns = "))

# Initialize an empty list to store the matrix
a = []

# Loop to input the matrix elements row-wise
for i in range(n):
    b = []  # Temporary list to store each row
    for j in range(n1):
        g = int(input(f"Enter the matrix element at row {i+1}, column {j+1} = "))
        b.append(g)  # Add element to the row
    a.append(b)  # Add the completed row to the matrix

print("\nOriginal Matrix:")
for row in a:
    print(row)

# Modify the matrix by setting a particular element to NaN
if n > 2 and n1 > 1:  # Ensure the index [2][1] is within the bounds
    a[2][1] = np.nan

# Convert the list of lists into a NumPy array
a1 = np.array(a)

# Print the final matrix
print("\nThe matrix with np.nan at [2][1]:\n", a1)