<b>Q.No. 1: Find A$^3$ - 3A + 20I for any A of order 4.</b>

<b>Q.No. 2: Check Commutativity for addition and multiplication of 2 matrices and display the conclusion.</b> np.allclose(A,B)    /  np.array_equal(A,B)

<b> Q.No3: Write a program to check whether the given matrix is symmetric or skew symmetric.<br><br>
(i)$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 5 & 6 \\ 3 & 6 & 9\end{bmatrix}$$
</b>

<b>Q4: Write a program to define a 4X4 matrix and perform the following manupulations-
$$\begin{bmatrix} 2 & 3 & 4 & 5 \\ 8 & 10 & 20 & 1 \\ 6 & 10 & 21 & 20 \\ 7 & 5 & 2 & 0\end{bmatrix}$$
</b>
(i) Find the square root of each element in the 3rd row.<br>
(ii) Add the corresponding elements of the first and second columns.<br>
(iii) Extract the first column of the matrix and reshape it into a 2X2 matrix.

In [2]:
import numpy as np 
A = np.array([[2,3,4,5]
            ,[8,10,20,1]
            ,[6,10,21,20]
            ,[7,5,2,0]])

sum = A[:,0 ] + A[:,1]
print("Sum = ",sum)


Sum =  [ 5 18 16 12]


In [7]:
import numpy as np
A = np.array ([[2,3,4,5],
               [8,10,20,1],
               [6,10,21,20],
               [7,5,2,0]])
I = np.eye(4)

A_cubed = np.linalg.matrix_power(A,3)

three_A = 3*A

twenty_I = 20* I

result = A_cubed - three_A + twenty_I
print(result)

[[ 2619.  3347.  5944.  3761.]
 [10128. 12739. 22046. 14521.]
 [11572. 14674. 25674. 16258.]
 [ 2419.  3193.  5808.  3841.]]


In [6]:
####Q1
import numpy as np
A = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])
I = np.identity(4,dtype=int)
M = np.dot(A,A)
F = np.dot(M,A)
C = F - 3*A + 20*I
print("A^3 - 3A + 20I = ")
print(C)

A^3 - 3A + 20I = 
[[1025 1018 1031 1044]
 [2593 2626 2619 2632]
 [2965 2952 2959 2926]
 [1377 1364 1351 1358]]


In [ ]:
####Q2
A = np.array([[1,2,3],[3,4,5],[6,7,8]])
B = np.array([[-1,4,0],[4,-5,-7],[9,8,0]])
print("A = ")
print(A)
print("B = ")
print(B)
LA = A+B
print("A + B = ")
print(LA)
3
RA = B+A
print("B + A =")
print(RA)
if(np.allclose(LA,RA)):
    print("A + B = B + A")
    print("Hence Addition of Matrices is Commutative.")
else:
    print("A + B ≠ B + A")
    print("Hence Addition of Matrices is NOT Commutative.")
LM = np.dot(A,B)
print("AB = ")
print(LM)
RM = np.dot(B,A)
print("BA = ")
print(RM)
if(np.allclose(LM,RM)):
    print("AB = BA")
    print("Hence Multiplication of Matrices is Commutative.")
else:
    print("AB ≠ BA")
    print("Hence Multiplication of Matrices is NOT Commutative.")

In [4]:
###Q3
import numpy as np
A=np.array([[1,2,3],[2,5,6],[3,6,9]])
T=np.transpose(A)
print("A = \n",A)
print("\nT = \n",T)
print("\n-T = \n",-T)
if(np.allclose(A,T)):
    print("\nA = T")
    print("A is a symmetric matrix")
elif(np.allclose(A,-T)):
    print("\nA = -T") 
    print("A is a skew symmetric matrix")
else:
    print("A is a neither a symmetric nor a skew symmetric matrix")

A = 
 [[1 2 3]
 [2 5 6]
 [3 6 9]]

T = 
 [[1 2 3]
 [2 5 6]
 [3 6 9]]

-T = 
 [[-1 -2 -3]
 [-2 -5 -6]
 [-3 -6 -9]]

A = T
A is a symmetric matrix


In [5]:
###Q4

import numpy as np
matrix = np.array([[2,3,4,5],[8,10,20,1],[6,10,21,20],[7,5,2,0]])
print("The given matrix is:")
print(matrix)

# (i) Find the square root of each element in the 3rd row
third_row_sqrt = np.sqrt(matrix[2, :])
print("\nSquare root of elements in the 3rd row:")
print(third_row_sqrt)

# (ii) Add the corresponding elements of the first and second columns
first_col = matrix[:, 0]
second_col = matrix[:, 1]
f = first_col + second_col
print("\nSum of corresponding elements of the first and second columns:")
print(f)

# (iii) Extract the first column of the matrix and reshape it into a 2x2 matrix
reshaped = np.reshape(matrix[:, 0], (2, 2))
print("\nFirst column of the matrix reshaped into a 2x2 matrix:")
print(reshaped)

The given matrix is:
[[ 2  3  4  5]
 [ 8 10 20  1]
 [ 6 10 21 20]
 [ 7  5  2  0]]

Square root of elements in the 3rd row:
[2.44948974 3.16227766 4.58257569 4.47213595]

Sum of corresponding elements of the first and second columns:
[ 5 18 16 12]

First column of the matrix reshaped into a 2x2 matrix:
[[2 8]
 [6 7]]
